GET http://localhost:8080/api/example
Accept: application/json

###

GET http://localhost:8080/api/example/42
Accept: application/json

###

POST http://localhost:8080/api/example/some-data
Content-Type: application/json

{
  "name": "some-data",
  "strings": ["blah", "blah-blah"]
}

###

GET http://localhost:8080/api/example/some-data
Accept: application/json

###

PUT http://localhost:8080/api/example/some-data
Content-Type: application/json

{
  "name": "some else data",
  "strings": ["blah", "blah-blah", "blah-blah-blah-blah!"]
}
