GET http://localhost:8080/api/file/
Accept: application/json

###

GET http://localhost:8080/api/file/docker-compose.yml
Accept: application/json

###

GET http://localhost:8080/api/file/research
Accept: application/json

###

GET http://localhost:8080/api/file/research/
Accept: application/json

###

GET http://localhost:8080/api/file/research/agents.md
Accept: application/json

###

GET http://localhost:8080/api/file/http/src/main/scala/dev/rudiments/hardcore/http/Router.scala
Accept: application/json

###