GET http://localhost:8080/api/routers/
Accept: application/json

###

GET http://localhost:8080/api/routers
Accept: application/json

###

GET http://localhost:8080/api/routers/types
Accept: application/json

###

GET http://localhost:8080/api/all/
Accept: application/json