GET http://localhost:8080/api/types/
Accept: application/json

###

GET http://localhost:8080/api/types
Accept: application/json

###

GET http://localhost:8080/api/types/relations/
Accept: application/json

###

GET http://localhost:8080/api/types/Type
Accept: application/json

###

GET http://localhost:8080/api/types/Field
Accept: application/json
