env:
  global:
    - # GITHUB_SECRET_TOKEN
    - secure: "Z52tkyglo1sysmAYfBAJ3k6H20czqZPJn/uU9drsTdpXKr0Vgj3UwTtzznxmBwgAevV7x+bVYsu9idvAu9vbH+dOUtxAg45wWLMLfLx6pFDQ01LlgB+6vpWywq/CigGzF5l+qBOMaAaXJ2oLEriMpBJsSpo74VhN23nxZqobUAnoKio9XjkmoQnjPEqu4kjas3b8II1HwSB9G6vR/19pBBNoqnMsbR0OThgEy6ao6AFBBLo8BHgB0h+fB3zCXjc0TX5aLmeOW1wH0rvOlnWoXAeKwDys8k0sU9BXA+QDm4r9LWXfv3/pFcyn62R7Idgt1pb+qH5Q1HbGaLfMtP06Ff/ZwwByogNvrh3XGH1TvoG51SKcZW/E455E4m2LZmeHv8FawMQWEv6I/aVPLa5KH5Ulbt513fp9OHgbM79rn+U4Dhl52O/J7mGgeJJfOBL9bQEzGRLaDl3nFSVEtAMcOBndHLZ7ZnAK+0gv+BajFkcXOSjMlw4YnyO8mlJn5pXYDhfZzWmGWTaIXJoTVUbxrn83WXWqLofBtXfCqx/9hmImQOPurZXIZxW8u3BjgUu+Ov7nJ9WiqHkxz92upeWgZEdIqi39pKrgxruhQR6rmpdLzJdcMIMhMIGcw1nBkJQxDnIAReHyTGehASmNycuRtYTwRwUF0ug5MA0hWCIYn24="
    - # SONATYPE_USERNAME
    - secure: "ffdiCB+9ulFy3bnvnGjz+vjwPVzD7PrOOqMHcloA+65poTeaWFM278wZn83JtSEskhByEraHfVbuboBfK/ABtl1OqAaeDJd6jLMRrdpocfOx395p0FbfqH/IoI5MO5hMHRzxJSUWUObuQFLonQSQYQBJtrYVTW5qiwE+gZrlgcBpQAfkm9NRPFkx2W90QNFHGxTKQK5oqHw8xEX9Na/5WofSnyB4KKX6GH6j3KI7yb8opoc2cLR0LINIBB7NINJB13Mdwe67wV7x4+8ro8hVWFuMEQQEM65Cjvd0CCvSNCakEJhpY4qBg2cCQbmDpifeS3v4PXVQ9lSRiZo7lOiTXpm9dZPImhudn3O2a52IkaLeaylrH1dyneEgE9neQher5jDwPO1miV4Y13Wl7PC2c/v58EHhMUz2c8hC08IvW7wSkJV/LAPi3T2mDpQROoctXOXXmGujWAKwg+gyFkdYrpbYkqjSAlWkKMirWnF39Fc0yyaQv/erssM64xY9ZqyTa570080Leo8Yf831/Zbletu5xNggZBiFf2y40HHuAPx4nsyBUIBOP0yO4vVWm0t2752BdVPVGqzhmotKcDBfpkyFlf4+zC1/dXORlviUxtV/NiMPqVefgxw3eVDbzrcyqbHgANc4PFf255CxATpxCv5o5PhAI5Wg0s443AXFbVw="
    - # SONATYPE_PASSWORD
    - secure: "y1BnqyyangwSM6clt5vodMtH5LxclQqzB3YM3iOqkAGxG0DEOUynrybc+nXfAYKcbDhLLRIXCHJ0a4XHHX0sMz2OmdyH60pm+IjS7NhzpY7jmVbVnV75GdRXh4keQ8op5AyNp2PuQaStdhbcCRhKnPrWkKDDc4OreEM2IifWVM9U2rMuEnvSYcrHSA7cox6CL0DvrGx4/SyyU+DmSJrWVbkDI9N7KD+oYugP1At6lZql9FXnE9SL0OuyApQ39j8g1vsetC9ppO7hwoQddGJGUnOYOob1RiRec4mv6em6g2Q3Vy4B5xvQfIYtsFEs5I6J3ZDUvc7f9mptyfUiWwtWBCctJD0I6qy0QHmaFgFg9GLjWWKlUh+QWYf8oW7u69FCIJ/S6HR1/E/weWTcuiBBncWhPKDcNfty8oA8lvm0JrQk2hv/eDQ5Ktch8+cbuGVhWybTV9WxtIfT6zYkANOh5rvwGK/eDLO4GhCS691kfULvrkdQnX/4p6VbGEYsrK0PXJ3EGocMmzpQkzgU4qivdiUE/0eGYyYj4rMKXWypSyfnkD0s1J9+FJCT/3DB1Zv82XXp527LDZZCotirkzHgDIsJq3xjynWtOyoUOXIdaKBGuIpSY+7AhGr7zWA+YUXeCMghw/rirweYNwnOE24/WWPyoSXMi39Bp8TlH5mGpUk="
    - # GPG_KEY_ID
    - secure: "HN3kNoGWj+dXUDPgBZXaXHOO/KyrgyUkt1SdxqTBfCN/e6FbdZlshM2oNbncbNNQc8l2Xu8W9PUNoQBmAl8WyQVHA0OAt6dJzlQtiK1qx8YqAjqBkl0Tmey7Ih9sGBXaHaMgYcVi7lAhh7sPBOmZ8A3FOQijn1E8xn4MePNOsB5rEFY7wlxFDLlKkg+pqlWKflBCRXNtsY5MtDLjiCaZsrbKKVfyOyy89UJwja3zFwRAlG1tbW9IxGabWOt0L9oYj1EdNbdj/gdeI26eVGEKczJm/3vd8WGymOXxUPgOdpYVbLysei11N1A2c71T2uqy0/zp2JKdp7INU9DnVNfE+VB01EAp99NxPETqmW92DnhcypbHTFEHX3kVdF4ERQmQ0OuUUePpuUZ4SgTrRy/xLoFVPGM8iGqZIgh1MTpsP9hsukZcP4P/6+8C2J9+oI7mlnSQXppgoSnzS5pBjB4UukHwtOI/sRs1/fJBfIY44ZYx0hl5k2ZmzvzZQ1fD1sF9StA2XeZ2YSq8vPiMH5mEECHyFjRglsMre6/j/moSBrubV/Vhf7Wl+LXnLWnoc7f5feeuj1eCkqJUJ72SxDKwPN5CQUpfhlWZlGX/+ZqsGowQdPPzhom+5Y3DWejVt6yJcOKf1cAi+8lhZsTyODt2oMyBp9E8wdWGHeULaYES4E4="
    - # GPG_PASSPHRASE
    - secure: "imicKEKGEu5BJdUJEAVxfEGHA1cQO48K2GEuGpJJNM0sXXHCgmdFVkKbWPqdRilynWTZHHI4ZOq725s3fBXuffD9fwSGhki62diNhdo0LQxsTbwGzdkBxj6HdwiaXT097Xk24GHcB44fKBa5NF9Qu58OvUmaCRTINjsySVOxjH9vNAeQUXigir/a3/41HiV6TfX2ky+XzfQOEBAXKYJSyJC/Gre+GPjfSS4pntEqWszrO/vXLquO87Lm6klX0TpAMv1YchLz5ccAAHTtUoSnDAeB2QOv2fB4gA8bTJECIGPGWEhRcqlFMHi4cfhjOrf2/ak+hN4WmjkgQchs7MX9dorhnC2U81YuDsP2epvBxNc8C6ujk6phgnQ8y+Xpa8ppl50dWbrKUdpdE/RHQ2ZyghZAZ8flWk28bg0Cso+F6KgqpURp3htDY6bsGvhDlZySCVUkKf9HRNe7lURVZJfZ6FUOvHNlkhZZJQqQvuaz7dKbFoTJUCE9D+dGodNGYj4F383B/A9DRHDOCkfI1OQGnhP6UzdQVfgLHYgAKhcvP7qHeW7FFbJmmpggrfiwZcY734KI3OiAh0Q+Cyv6IKJhlgE9HmleavRVf8epNb3mFEsdw/U/PydCicO+DKivaMbBPfYwg/vglQPxgTlSGzsfBqGCVCh6xN0t+j++q/HwRN4="
    - GPG_KEY_LOCATION=".travis/secret.gpg"
    - ENCRYPTED_GPG_KEY_LOCATION=".travis/secring.gpg.enc"
    - SONATYPE_REPO_URL="https://oss.sonatype.org/service/local/staging/deploy/maven2/"

language: scala
scala:
  - 2.12.8

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: ./gradlew build
    - stage: release
      name: "Release to maven central"
      if: branch = master
      before_script: openssl aes-256-cbc -K $encrypted_128b0dd6d06b_key -iv $encrypted_128b0dd6d06b_iv -in $ENCRYPTED_GPG_KEY_LOCATION -out $GPG_KEY_LOCATION -d
      script: ./gradlew uploadArchives
    - stage: snapshot
      name: "Publish snapshots to maven central"
      if: branch = develop
      before_script: openssl aes-256-cbc -K $encrypted_128b0dd6d06b_key -iv $encrypted_128b0dd6d06b_iv -in $ENCRYPTED_GPG_KEY_LOCATION -out $GPG_KEY_LOCATION -d
      script: ./gradlew uploadSnapshots

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
