GET http://localhost:8765/api/domain
Accept: application/json

###

GET http://localhost:8765/api/domain/SpecExample
Accept: application/json

###

POST http://localhost:8765/api/domain
Content-Type: application/json

{
  "name": "AbstractExample",
  "thing": {
    "type": "Abstract",
    "name": "AbstractExample",
    "fields": {}
  },
  "is": []
}

###

POST http://localhost:8765/api/domain
Content-Type: application/json

{
  "name": "TheExample",
  "thing": {
    "type": "The",
    "name": "TheExample"
  },
  "is": []
}


###

POST http://localhost:8765/api/domain
Content-Type: application/json

{
  "name": "SpecExample",
  "thing": {
    "type": "Spec",
    "name": "SpecExample",
    "fullName": "dev.rudiments.Examples.SpecExample",
    "fields": {
      "b": {
        "thing": {
          "type": "Bool"
        },
        "isRequired": true
      }
    }
  },
  "is": []
}

###

PUT http://localhost:8765/api/domain/SpecExample
Content-Type: application/json

{
  "name": "SpecExample",
  "thing": {
    "type": "Spec",
    "name": "SpecExample",
    "fullName": "dev.rudiments.Examples.SpecExample",
    "fields": {
      "a": {
        "thing": {
          "type": "UUID"
        },
        "isRequired": true
      },
      "b": {
        "thing": {
          "type": "Bool"
        },
        "isRequired": true
      }
    }
  },
  "is": []
}
