name: Rudiments repository builds and coverage reports

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-cover:
    env:
      TESTCONTAINERS_RYUK_DISABLED: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build, Test, Generate Scoverage Report with Gradle
        run: ./gradlew build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./build/reports/scoverage
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
