name: Push latest Rudiments snapshots to Maven Snapshots repo

on:
  push:
    branches: [ develop ]

jobs:
  push-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Push latest Rudiments snapshots to Maven Snapshots repo
        run: ./gradlew test uploadArchives -PnexusUsername=${{ secrets.sonatype_username }} -PnexusPassword=${{ secrets.sonatype_password }}
